version: '3'

volumes:
  data:
  cache:
  log:

services:

  kinder:
    image: docker.io/effex7/kinder:latest
    container_name: k-inder
    ports:
      - 5000:5000
    volumes:
      - data:/data
      - cache:/cache
      - log:/log
    environment:
      # For accessing the Kodi API
      - KT_KODI_USERNAME=kodi
      - KT_KODI_PASSWORD=kodi
      - KT_KODI_HOST=127.0.0.1
      - KT_KODI_PORT=8080
      # Which overlays should be displayed on the poster
      - KT_OVERLAY_TITLE=True
      - KT_OVERLAY_DURATION=False
      - KT_OVERLAY_GENRES=True
      - KT_OVERLAY_WATCHED=False
      - KT_OVERLAY_AGE=False
      # For accessing samba movie share (for exported posters)
      - KT_SMB_USER=samba
      - KT_SMB_PASSWORD=samba
      # prefered image fetching order
      - KT_IMAGE_PREFERENCE=kodi_thumbnail, kodi_art, kodi_file, tmdb, imdb
      # none : No action for the perfect match will be provided
      # play : Direct play in kodi for the perfect match will be provided
      - KT_MATCH_ACTION=none
      # How many TOP/FLOP movies should be displayed in the stats?
      - KT_TOP_COUNT=3
      - KT_FLOP_COUNT=3
      # 3rd party API settings ( http://www.omdbapi.com/ https://api.themoviedb.org/ )
      - KT_OMDB_API_KEY=e26c797e
      - KT_TMDB_API_KEY=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2NjE0NWZjM2MxYzRhYzc0YmRiMTA0M2Q0MmI3MDA3YiIsIm5iZiI6MTc0OTg1Mjc0NS44ODUsInN1YiI6IjY4NGNhMjQ5OTA1NDM2ZjFhZTNkZjJmOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.NhAxayBq7-Un3tjKWHkWdahkV3e-AbHgUnLGjxuvG8g
      - KT_TMBD_API_LANGUAGE=de-DE
      - KT_TMBD_API_REGION=de
      # Default filter settings
      ## e.g. : Horror,Action
      - KT_FILTER_DEFAULT_DISABLED_GENRES=
      - KT_FILTER_DEFAULT_MUST_GENRES=
      ## 0 :  0 years
      ## 1 :  6 years
      ## 2 : 12 years
      ## 3 : 16 years
      ## 4 : 18+ years
      - KT_FILTER_DEFAULT_MAX_AGE=4
      ## 0 :  30 minutes
      ## 1 :  60 minutes
      ## 2 :  90 minutes
      ## 3 : 120 minutes
      ## 4 : 135 minutes
      ## 5 : 150 minutes
      ## 6 : 165 minutes
      ## 7 : 180 minutes
      ## 8 : 210 minutes
      ## 9 : 240 minutes
      ## 10: 240+ minutes
      - KT_FILTER_DEFAULT_MAX_DURATION=10
      - KT_FILTER_DEFAULT_INCLUDE_WATCHED=True
      # For developing
      - KT_SERVER_HOST=0.0.0.0
      - KT_SERVER_SWAGGER=False
      - KT_SERVER_DEBUG=False
      - KT_CACHE_FOLDER=/cache
      - KT_LOG_FOLDER=/log
      - KT_LOG_LEVEL=INFO
      - KT_SERVER_SECRET_KEY=secret_key
      - KT_DATABASE_URI=sqlite:////data/database.sqlite3
      # Enables an internal Dummy-Kodi API; still needs to set correct KT_KODI_HOST and KT_KODI_PORT (usually 5000)
      - KT_KODI_ENABLE_DEMO_API=False
