version: '3'

volumes:
  data:
  cache:
  log:

services:

  kinder:
    image: docker.io/effex7/kinder:latest
    container_name: k-inder
    ports:
      - 5000:5000
    volumes:
      - data:/data
      - cache:/cache
      - log:/log
    environment:
      # For accessing the Kodi API
      - KT_KODI_USERNAME=kodi
      - KT_KODI_PASSWORD=kodi
      - KT_KODI_HOST=127.0.0.1
      - KT_KODI_PORT=8080
      - KT_KODI_TIMEOUT=1
      # For accessing the Emby API
      - ENV KT_EMBY_TIMEOUT=2
      - ENV KT_EMBY_URL=http://localhost/
      - ENV KT_EMBY_API_KEY=
      # For accessing the Jellyfin API
      - KT_JELLYFIN_TIMEOUT=2
      - KT_JELLYFIN_URL='http://localhost/'
      - KT_JELLYFIN_API_KEY=
      # For accessing the Plex API
      - KT_PLEX_TIMEOUT=2
      - KT_PLEX_URL='http://localhost/'
      - KT_PLEX_API_KEY=
      # Which overlays should be displayed on the poster
      - KT_OVERLAY_TITLE=True
      - KT_OVERLAY_DURATION=True
      - KT_OVERLAY_GENRES=True
      - KT_OVERLAY_WATCHED=True
      - KT_OVERLAY_AGE=True
      # For accessing samba movie share (for exported posters)
      - KT_SMB_USER=samba
      - KT_SMB_PASSWORD=samba
      # none : No action for the perfect match will be provided
      # play : Direct play in kodi for the perfect match will be provided
      - KT_MATCH_ACTION=none
      # How many TOP/FLOP movies should be displayed in the stats?
      - KT_TOP_COUNT=3
      - KT_FLOP_COUNT=3
      # 3rd party API settings ( http://www.omdbapi.com/ https://api.themoviedb.org/ )
      - KT_OMDB_API_KEY=e26c797e
      - KT_TMDB_API_KEY=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2NjE0NWZjM2MxYzRhYzc0YmRiMTA0M2Q0MmI3MDA3YiIsIm5iZiI6MTc0OTg1Mjc0NS44ODUsInN1YiI6IjY4NGNhMjQ5OTA1NDM2ZjFhZTNkZjJmOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.NhAxayBq7-Un3tjKWHkWdahkV3e-AbHgUnLGjxuvG8g
      - KT_TMDB_API_LANGUAGE=de-DE
      - KT_TMDB_API_REGION=DE
      - KT_TMDB_API_TIMEOUT=3
      - KT_TMDB_API_INCLUDE_ADULT=false
      # Possibilitys to fetch movie lists from netflix.
      # The movies will NOT be presented in the order you define here.
      # But the first 200 of the given order will be randomized an be presented to you.
      # original_title.[asc|desc]
      # popularity.[asc|desc]
      # revenue.[asc|desc]
      # primary_release_date.[asc|desc]
      # title.[asc|desc]
      # vote_average.[asc|desc]
      # vote_count.[asc|desc]
      - KT_TMDB_API_DISCOVER_SORT=popularity.desc
      # Total movies to be fetched from the TMDB API to be presented for voting.
      # Values > 1000 will be cut to 1000, so the given api key will not be escausted to fast ;-)
      - KT_TMDB_API_DISCOVER_TOTAL=200
      # Disable some filter.
      # more specific: Hide them from the "Session Create" screen.
      # This means the FILTER_DEFAULT settings will still apply, but you can not change them.
      - KT_FILTER_HIDE_PROVIDER=False
      - KT_FILTER_HIDE_DISABLED_GENRES=False
      - KT_FILTER_HIDE_MUST_GENRES=False
      - KT_FILTER_HIDE_MAX_AGE=False
      - KT_FILTER_HIDE_MAX_DURATION=False
      - KT_FILTER_HIDE_INCLUDE_WATCHED=False
      - KT_HIDE_END=False
      # Default filter settings
      # Comma seperated list of default sources K-inder should fetch movies from.
      # Valid (single) values are:
      # kodi
      # netflix
      # amazon_prime
      # amazon_video
      # disney_plus
      # paramount_plus
      # apple_tv_plus
      # example for multiple would be : 'kodi,netflix')
      # Some sources may need further configuration (e.g.: kodi needs KT_KODI_USERNAME, KT_KODI_PASSWORD, KT_KODI_HOST)
      - KT_FILTER_DEFAULT_PROVIDER=kodi
      ## e.g. : Horror,Action
      - KT_FILTER_DEFAULT_DISABLED_GENRES=
      - KT_FILTER_DEFAULT_MUST_GENRES=
      ## 0 :  0 years
      ## 1 :  6 years
      ## 2 : 12 years
      ## 3 : 16 years
      ## 4 : 18+ years
      - KT_FILTER_DEFAULT_MAX_AGE=4
      ## 0 :  30 minutes
      ## 1 :  60 minutes
      ## 2 :  90 minutes
      ## 3 : 120 minutes
      ## 4 : 135 minutes
      ## 5 : 150 minutes
      ## 6 : 165 minutes
      ## 7 : 180 minutes
      ## 8 : 210 minutes
      ## 9 : 240 minutes
      ## 10: 240+ minutes
      - KT_FILTER_DEFAULT_MAX_DURATION=10
      - KT_FILTER_DEFAULT_INCLUDE_WATCHED=True
      # Endconditions
      # Vote will always be over when no movies for voting are left
      - KT_DEFAULT_END_MAX_MINUTES=-1
      - KT_DEFAULT_END_MAX_VOTES=-1
      - KT_DEFAULT_END_MAX_MATCHES=-1
      # For developing
      - KT_SERVER_HOST=0.0.0.0
      - KT_SERVER_SWAGGER=False
      - KT_SERVER_DEBUG=False
      - KT_CACHE_FOLDER=/cache
      - KT_LOG_FOLDER=/log
      - KT_LOG_LEVEL=INFO
      - KT_SERVER_SECRET_KEY=secret_key
      - KT_DATABASE_URI=sqlite:////data/database.sqlite3
      - KT_EXECUTOR_WORKERS=3
