name: Build latest Docker image and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t effex7/kinder:latest .

      - name: Build git history
        run: |
          git log --online > HISTORY.md

      - name: Tag Docker image with sha tag
        run: |
          TAG=sha-$(echo $GITHUB_SHA | cut -c1-7)
          echo "TAG=$TAG" >> $GITHUB_ENV
          docker tag effex7/kinder:latest effex7/kinder:$TAG

      - name: Push Docker image
        run: |
          docker push effex7/kinder:${{ env.TAG }}
          docker push effex7/kinder:latest