name: Build test Docker image and push to Docker Hub

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # needed for the history generation
          ref: test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build git history
        run: |
          git log --oneline > HISTORY.md
          docker buildx create --use

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            effex7/kinder:test
          platforms: linux/amd64,linux/arm64,linux/arm/v7
